config/routes.rb
Rails.application.routes.draw do
 
  get 'new/sessions'

  get 'new/new'

  get 'sessions/new'

  # get 'auth/:provider/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  # get 'signout', to: 'sessions#destroy', as: 'signout'

  # resources :sessions, only: [:create, :destroy]
  # resource :home, only: [:show]

  root to: 'sessions#new'

  get 'home/show'


	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'static_pages#home'
	
	get '/home', to: 'static_pages#home'

	get '/help', to: 'static_pages#help'

	get '/about', to: 'static_pages#about'

	get '/contact', to: 'static_pages#contact'

	get '/signup', to: 'users#new'
	post '/signup', to: 'users#create'

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'

	delete 'logout', to: 'sessions#destroy'

	get 'welcome/index'

	resources :users
	resources :microposts

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="container pt-3 my-md-3 pt-md-3 border-top">
  	<div class="row">
  		<div class="col-12 col-md">
        <%= image_tag "logo-footer.png", size:"24", class: "mb-1 mt-1 align-middle" %>
  			<small class="mb-3 text-muted ml-md-3 align-middle">&copy; Airbnb, Inc.</small>
  		</div>
  		<div class="mr-md-3">
  			<a href="https://www.facebook.com/bootsnip" id="social-fb" class="fa fa-facebook-square fa-2x social"></a>
        <a href="https://twitter.com/bootsnipp" id="social-tw" class="fa fa-twitter-square fa-2x social"></a>
        <a href="https://plus.google.com/+Bootsnipp-page" id="social-gp" class="fa fa-google-plus-square fa-2x social"></a>
        <a href="https://instagram.com/+Bootsnipp-page" id="social-ig" class="fa fa-instagram fa-2x social"></a>
  		</div>
  	</div>
  </footer>
</div>

app/views/shared/_header.html.erb
<!-- shared/header -->
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <%= link_to image_tag("logo-header.png", class: 'logo-image',  size: "30"), root_path , class: "navbar-brand"  %>
  
  <a class="btn btn-outline-primary ml-auto" href="#">Become a Host</a>
  <nav class="my-1 my-md-0 mr-md-3 ml-md-3">
    <%= link_to "Help", help_path, class: "p-2 text-dark" %>
    <%= link_to "Users", '#', class: "p-2 text-dark" %>
		<% if logged_in? %>
			<li class="nav-item dropdown" style="display: inline-block;">
        <a class="nav-link dropdown-toggle p-2 text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Profile', current_user, class: 'dropdown-item' %>
          <%= link_to 'Settings', '#', class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Log out', logout_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
		<% else %>
	    <%= link_to "Sign Up", signup_path, class: "p-2 text-dark" %>
	    <%= link_to "Log In", login_path, class: "p-2 text-dark" %>
    <% end %>
  </nav>
</div>